clc;
clear;

% Read the CSV generated by Python
data = readtable('screen_attention_log.csv');

% Check enough rows exist
if height(data) < 2
    error('Not enough data in screen_attention_log.csv');
end

% Validate required time column
if ~ismember('unix_time', data.Properties.VariableNames)
    error('CSV must contain a unix_time column.');
end

% Extract timestamp vector
t = data.unix_time;

% Build look flag from available columns
if ismember('looking_at_screen', data.Properties.VariableNames)
    lookFlag = data.looking_at_screen;
elseif ismember('state', data.Properties.VariableNames)
    stateText = string(data.state);
    lookFlag = double(stateText == "LOOKING_AT_SCREEN");
else
    error('CSV must contain either looking_at_screen or state column.');
end

% Ensure numeric and clean
t = double(t);
lookFlag = double(lookFlag);
valid = isfinite(t) & isfinite(lookFlag);
t = t(valid);
lookFlag = lookFlag(valid);

if numel(t) < 2
    error('Not enough valid rows after cleaning NaN/Inf values.');
end

% Compute time differences between samples
dt = diff(t);

% Keep only positive intervals to avoid duplicate/out-of-order timestamps
validDt = dt > 0;
dt = dt(validDt);

% Use lookFlag for each interval based on the starting sample
lookFlagInterval = lookFlag(1:end-1);
lookFlagInterval = lookFlagInterval(validDt);

if isempty(dt)
    error('No positive time intervals found in unix_time.');
end

% Total monitored time
totalTime = sum(dt);

% Time looking at screen
lookingTime = sum(dt .* lookFlagInterval);

% Proportion and percentage
proportionLooking = lookingTime / totalTime;
percentageLooking = 100 * proportionLooking;

fprintf('Total monitored time: %.2f seconds\n', totalTime);
fprintf('Time looking at screen: %.2f seconds\n', lookingTime);
fprintf('Proportion looking at screen: %.4f\n', proportionLooking);
fprintf('Percentage looking at screen: %.2f%%\n', percentageLooking);

% Optional plot
figure;
stairs(t - t(1), lookFlag, 'LineWidth', 1.5);
xlabel('Time (s)');
ylabel('Looking at screen');
title('Looking-at-screen state over time');
ylim([-0.1 1.1]);
grid on;